version: "3"
services:
  strapi:
    container_name: lms-strapi
    image: ${DOCKERHUB_USERNAME}/balkar-back:mooc
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      URL: ${URL}
      DEEPL_API_KEY: ${DEEPL_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_PI_SECRET: ${STRIPE_WEBHOOK_PI_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  frontend:
    container_name: lms-frontend
    image: ${DOCKERHUB_USERNAME}/balkar-front:mooc
    restart: unless-stopped
    env_file: .env
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
    ports:
      - "3005:80"
    networks:
      - strapi

  strapiDB:
    container_name: lms-strapi-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    networks:
      - strapi
    command: -p 5433
    expose:
      - "5433"

networks:
  strapi:
    name: Strapi
    driver: bridge